name: .NET

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - name: Restore dependencies
      run: dotnet restore Piloto.Api.sln
    - name: Build
      run: dotnet build Piloto.Api.sln --no-restore
    - name: Test with coverage
      run: dotnet test Piloto.Api.UnitTests/Piloto.Api.UnitTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/
    - name: List TestResults directory
      run: ls -la Piloto.Api.UnitTests/TestResults
    - name: Generate coverage report
      run: reportgenerator -reports:Piloto.Api.UnitTests/TestResults/coverage.cobertura.xml -targetdir:Piloto.Api.UnitTests/TestResults/CoverageReport
    - name: Check coverage threshold
      run: |
        coverage=$(grep -oP '(?<=<coverage line-rate=")[^"]*' Piloto.Api.UnitTests/TestResults/CoverageReport/index.html)
        coverage=$(echo "$coverage * 100" | bc)
        if (( $(echo "$coverage < 65" | bc -l) )); then
          echo "Code coverage ($coverage%) is below the threshold of 65%."
          exit 1
        fi
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: Piloto.Api.UnitTests/TestResults/CoverageReport

